# -*- coding: utf-8 -*-
"""mapasDeVendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTQ8BBGTw1zNzKEJkkCIZAcuPsjGlf4q
"""

import pandas as pd

tabela = pd.read_csv ("/Cidades (1).csv")
display(tabela)

import plotly.express as px

grafico = px.density_mapbox(tabela, lon="geolocation_lng", lat="geolocation_lat", z="quantidade", mapbox_style="open-street-map", zoom=3, radius=10)

grafico.update_layout(margin = {"r":0,"t":0,"b":0,"l":0})



grafico.show()

